### ISSUE TITLE
pydantic version 2.x getting installed on a clean install 

### ISSUE THREAD

**Issue by pjr** [Shoobx/pyocf#8]
```bash
(.venv) [~/src/python/captable]$ cat test_pyocf.py
from pyocf.objects.stakeholder import Stakeholder

(.venv) [~/src/python/captable]$ python --version
Python 3.11.4
(.venv) [~/src/python/captable]$ python test_pyocf.py
Traceback (most recent call last):
  File "/Users/philipreynolds/src/python/captable/test_pyocf.py", line 1, in <module>
    from pyocf.objects.stakeholder import Stakeholder
  File "/Users/philipreynolds/src/python/captable/.venv/lib/python3.11/site-packages/pyocf/objects/stakeholder.py", line 15, in <module>
    from pyocf.types.address import Address
  File "/Users/philipreynolds/src/python/captable/.venv/lib/python3.11/site-packages/pyocf/types/address.py", line 14, in <module>
    from pyocf.types.countrycode import CountryCode
  File "/Users/philipreynolds/src/python/captable/.venv/lib/python3.11/site-packages/pyocf/types/countrycode.py", line 15, in <module>
    class CountryCode(SimpleBaseModel):
  File "/Users/philipreynolds/src/python/captable/.venv/lib/python3.11/site-packages/pyocf/types/countrycode.py", line 18, in CountryCode
    __root__: constr(regex=r"^[A-Z]{2}$")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: constr() got an unexpected keyword argument 'regex'
(.venv) [~/src/python/captable]$ pip list
Package           Version
----------------- -------
annotated-types   0.5.0
pip               23.2.1
pydantic          2.1.1
pydantic_core     2.4.0
pyocf             1.0.1
setuptools        68.0.0
typing_extensions 4.7.1
(.venv) [~/src/python/captable]$ pip install pydantic==1.10

Collecting pydantic==1.10
  Using cached pydantic-1.10.0-cp311-cp311-macosx_11_0_arm64.whl (2.5 MB)
Requirement already satisfied: typing-extensions>=4.1.0 in ./.venv/lib/python3.11/site-packages (from pydantic==1.10) (4.7.1)
Installing collected packages: pydantic
  Attempting uninstall: pydantic
    Found existing installation: pydantic 2.1.1
    Uninstalling pydantic-2.1.1:
      Successfully uninstalled pydantic-2.1.1
Successfully installed pydantic-1.10.0
(.venv) [~/src/python/captable]$ python test_pyocf.py
(.venv) [~/src/python/captable]$
```

`setup.cfg` just specifies anything greater than 1.10.0 will do. Need to explicitly say <2.0.0
```python
pydantic >= 1.10.0, <2.0.0
```

**Comment by regebro** [comment]
Thanks! Fixed!
